name: Deploy to dokku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Dokku deploy
      uses: vitalyliber/dokku-github-action@57b7fd8b32adfe7924e71123a60a988aa0f62d3f
      env:
        PRIVATE_KEY: ${{ secrets.DOKKU_DEPLOYMENT_SSH_PRIVATE_KEY }}
        HOST: app.etalab.studio
        PROJECT: suivi-ouverture
